// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ehaSHr37N1T20VB04g0vuyMWc_5ewb4',
    appId: '1:445959327668:web:0bbd983509a1cad3ff2ce1',
    messagingSenderId: '445959327668',
    projectId: 'flutter-apps-39644',
    authDomain: 'flutter-apps-39644.firebaseapp.com',
    storageBucket: 'flutter-apps-39644.firebasestorage.app',
    measurementId: 'G-8SBP326MJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0orNoYEtTHuegq_xw3xv7LCjbu71Ggn8',
    appId: '1:445959327668:android:1fc7356d11cbfaedff2ce1',
    messagingSenderId: '445959327668',
    projectId: 'flutter-apps-39644',
    storageBucket: 'flutter-apps-39644.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXUL2FYBnYPh4aJvjL8vlO9IUpJZHjAcw',
    appId: '1:445959327668:ios:9fb2f9a3398f4153ff2ce1',
    messagingSenderId: '445959327668',
    projectId: 'flutter-apps-39644',
    storageBucket: 'flutter-apps-39644.firebasestorage.app',
    iosBundleId: 'com.example.shoporiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXUL2FYBnYPh4aJvjL8vlO9IUpJZHjAcw',
    appId: '1:445959327668:ios:9fb2f9a3398f4153ff2ce1',
    messagingSenderId: '445959327668',
    projectId: 'flutter-apps-39644',
    storageBucket: 'flutter-apps-39644.firebasestorage.app',
    iosBundleId: 'com.example.shoporiaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8ehaSHr37N1T20VB04g0vuyMWc_5ewb4',
    appId: '1:445959327668:web:297f07f571502507ff2ce1',
    messagingSenderId: '445959327668',
    projectId: 'flutter-apps-39644',
    authDomain: 'flutter-apps-39644.firebaseapp.com',
    storageBucket: 'flutter-apps-39644.firebasestorage.app',
    measurementId: 'G-58LG3XQ00B',
  );
}
